import localFont from "next/font/local";
import "./globals.css";

const titilliumWebBold = localFont({
  src: "./fonts/TitilliumWeb-Bold.ttf",
  variable: "--font-titillium-web-bold",
});
const titilliumWebSemiBold = localFont({
  src: "./fonts/TitilliumWeb-SemiBold.ttf",
  variable: "--font-titillium-web-semi-bold",
});
const titilliumWebRegular = localFont({
  src: "./fonts/TitilliumWeb-Regular.ttf",
  variable: "--font-titillium-web-regular",
});
const titilliumWebLight = localFont({
  src: "./fonts/TitilliumWeb-Light.ttf",
  variable: "--font-titillium-web-light",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${titilliumWebBold.variable} ${titilliumWebLight.variable} ${titilliumWebRegular.variable} ${titilliumWebSemiBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
